### ISSUE TITLE
Navigation arrows and play/pause buttons are partly hidden

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/flexslider#12] opened 2021-04-20 14:48 UTC
On a site that's using Basis and Flexslider, the previous/next arrows and the play/pause are partly hidden. I can understand there being an `overflow: hidden` but it seems like it might need to be tweaked to not hide any of the icon. Or maybe there's a smarter way of doing it? Can the words be hidden in a different way?

![flexslider](https://user-images.githubusercontent.com/1071483/115416245-98da3a80-a1c5-11eb-9939-f6564e933217.png)

**Comment by laryn** [comment] 2021-04-28 18:28
@herbdool can you test to see if this tweak works for you?

```
.flexslider .flex-direction-nav a {
  height: 50px;
}
```

**Comment by laryn** [comment] 2021-04-28 18:42
Alternate upstream issue/fix: 

 - https://github.com/woocommerce/FlexSlider/issues/1752

**Comment by yorkshire-pudding** [comment] 2023-02-02 11:30
I can confirm that the second suggested fix from @laryn works well, and this seems to be better than setting a fixed height.  For reference, it is here:

```css
.flex-direction-nav a:before{
  line-height: 1;
}
```

Should it be added here, as the upstream PR has not been merged over a year after it was submitted?

**Comment by herbdool** [comment] 2023-02-03 17:08
@yorkshire-pudding I think your solution is the best. It works for me. Can you create a PR for this?

**Comment by yorkshire-pudding** [comment] 2023-02-03 17:48
@herbdool - happy to put together a PR, though it's @laryn 's solution (see the PR on the upstream fix in [this comment](https://github.com/backdrop-contrib/flexslider/issues/12#issuecomment-828691994)).

One thing I wasn't sure about was where to put it.  @jenlampton has created a css file at https://github.com/backdrop-contrib/flexslider/blob/1.x-2.x/css/flexslider_img.css - possibly this was to avoid a clash with the `flexslider.css` within the library, but it potentially sets a precedent for creating similarly named CSS files for additional requirements (e.g. `flexslider_nav.css`).

Or, could put all the CSS into say `css/flexslider.theme.css` (or `css/flexslider.custom.css`) and that avoids multiple CSS files to be loaded.

Thoughts @herbdool @laryn @jenlampton ?

**Comment by herbdool** [comment] 2023-06-29 04:27
I don't know why I didn't respond @yorkshire-pudding. I figure putting it in `flexslider_img.css` is fine since it has other lines about the nav. The file could be renamed in a different issue if needed. I created a PR. Want to test?

**Comment by yorkshire-pudding** [comment] 2023-06-29 08:25
@herbdool - tested that PR and it works well.  Thank you.

**Comment by herbdool** [comment] 2023-06-29 13:30
@jenlampton I've got a PR that fixes this long-standing issue, and it's been tested.

**Comment by herbdool** [comment] 2023-12-22 21:18
@jenlampton, @djzwerg also confirms that this PR fixes it. Is it merge worthy?

**Closed as completed** 2024-06-24 01:53 UTC
